[project]
name = "simple-agent"
version = "0.1.0"
description = "Simple AI agent."
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.22",
    "langchain>=0.3.25",
    "langchain-aws>=0.2.23",
    "langgraph>=0.4.5",
]
